
language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t guimaron/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true guimaron/docker-react npm run test
